# Generated by Django 4.2.29 on 2026-03-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tags",
            options={"verbose_name_plural": "Snippets"},
        ),
    ]
